services:
  db:
    image: postgres:17
    container_name: coreflow-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: coreflow-app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      APP_ENV: feature
      PDF_DIR: /app/generated_pdfs
      LOGO_PATH: /app/assets/logo.png
    ports:
      - "8000:8000"
    volumes:
      - ./generated_pdfs:/app/generated_pdfs:rw


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: coreflow-frontend
    ports:
    - "5173:5173"
    environment:
      - VITE_API_BASE_URL=https://localhost:8000
    depends_on:
      - app
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
