services:
  db:
    image: postgres:17
    container_name: coreflow-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
    container_name: coreflow-app
    depends_on:
      - db
    environment:
      APP_ENV: feature
      PDF_DIR: /app/generated_pdfs
      LOGO_PATH: /app/assets/logo.png
    ports:
      - "8001:8000"
    volumes:
      - ./generated_pdfs:/app/generated_pdfs:rw



volumes:
  pgdata:
