version: "3.9"

services:
  db:
    image: postgres:17
    container_name: coreflow-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build:
      context: .
    container_name: coreflow-app
    depends_on:
      - db
    environment:
      APP_ENV: feature
    ports:
      - "8001:8000"


volumes:
  pgdata:
